import type { Metadata } from "next";
import { Epilogue} from "next/font/google"
import "./globals.css";
import NavBar from "@/components/NavBar";

const EpilogueFont = Epilogue({
  weight: ['400','700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={EpilogueFont.className}
       
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
